name: Run tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 1"

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - run: |
          pip install -r requirements.txt
          pip install numpy scipy
        name: Install requirements
      - run: pip install flake8 pytest
        name: Install flake8 and pytest
      - run: python -m flake8 .
        name: Run flake8 checks
      - run: python -m pytest tests
        name: Run tests
